joint_limits:
  joint_s:
    has_velocity_limits: true
    max_velocity: .226
    has_acceleration_limits: false
    max_acceleration: 0
  joint_e:
    has_velocity_limits: true
    max_velocity: .296
    has_acceleration_limits: false
    max_acceleration: 0
  joint_r:
    has_velocity_limits: true
    max_velocity: .348
    has_acceleration_limits: false
    max_acceleration: 0
  joint_b:
    has_velocity_limits: true
    max_velocity: .348
    has_acceleration_limits: false
    max_acceleration: 0
  joint_t:
    has_velocity_limits: true
    max_velocity: .697
    has_acceleration_limits: false
    max_acceleration: 0
  joint_u:
    has_velocity_limits: true
    max_velocity: .296
    has_acceleration_limits: false
    max_acceleration: 0
  joint_l:
    has_velocity_limits: true
    max_velocity: .226
    has_acceleration_limits: false
    max_acceleration: 0
