<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	
	<xacro:include filename="$(find godel_robot_config)/urdf/asus_sensor_cal_macro.xacro"/>

	<!-- parameter list -->
	<xacro:property name="gripper_length" value="0.0"/>
	<xacro:property name="gripper_width" value="0.0"/>
	<xacro:property name="gripper_height" value="0.0"/>

	<xacro:macro name="blending_eff_definition" params="prefix eff_adjustment">

		<!-- link definition -->
			<link name="${prefix}eff_frame"/>

			<link name="${prefix}gripper_body">
				<visual>
					<geometry>
						<mesh filename="package://godel_robot_config/meshes/Deburring_eff.STL" />
					</geometry>
					<material name="silver">
						<color rgba="0.8 0.8 0.8 1"/>
					</material>
				</visual>
				<collision>
					<geometry>
						<mesh filename="package://godel_robot_config/meshes/Deburring_eff_Collision_Model.STL" />
					</geometry>
					<material name="another_blue2">
						<color rgba="0.38 0.54 0.83 1"/>
					</material>
				</collision>
			</link>

			<link name="${prefix}tcp_frame"/>
			<link name="${prefix}asus_mount"/>

		<xacro:asus_sensor_definitions prefix="${prefix}" parent_link="${prefix}asus_mount" />

		<!-- joint definitions -->
			<joint name="${prefix}gripper_to_palm" type="fixed">
				<parent link="${prefix}eff_frame"/>
				<child link="${prefix}gripper_body"/>
				<origin xyz="0 0 ${gripper_height * 0.5}" rpy="0 0 3.6651914"/>
			</joint>
		

			<joint name="${prefix}eff_frame_to_asus_mount" type="fixed">
				<parent link="${prefix}eff_frame"/>
				<child link="${prefix}asus_mount"/>
				<origin xyz="0 0 0.150" rpy="3.14 0 2.09"/>
			</joint>

			<joint name="${prefix}gripper_to_tcp" type="fixed">
				<parent link="${prefix}eff_frame"/>
				<child link="${prefix}tcp_frame"/>
				<origin xyz=" 0 ${gripper_length} ${eff_adjustment}" rpy="0 0 0"/>
			</joint>	
	</xacro:macro>
</robot>
